### ISSUE TITLE
How to visually indicate matches when consuming grep -nH output?

### ISSUE THREAD

**Issue by sdbbs** [rhysd/hgrep#16]
I have installed via `cargo install hgrep` under MINGW64 (Windows 10).

Assuming an input file like `myfile.c`:

```c
/*
 * foo has changed [...] and is now a 2-parameters function
 */
// foo(24)
int myvar = foo(42, 28);
```

... then if I run `hgrep` on the file directly (e.g. `hgrep foo myfile.c`) - then the matches are nicely indicated (in addition to corresponding line numbers):

![image](https://github.com/rhysd/hgrep/assets/48317456/2fdb96a6-3745-4300-b363-984202d7f1aa)

... however if I try to [Eat `grep -nH` output](https://lib.rs/crates/hgrep#readme-eat-grep--nh-output) (e.g. `grep -nH foo myfile.c | hgrep`) - then the matches are NOT indicated anymore, only the corresponding line numbers are:

![image](https://github.com/rhysd/hgrep/assets/48317456/a0cc05c1-33d7-45ef-951a-591f23729fbb)

Can I somehow get the matched substrings to be indicated, also when consuming `grep -nH` output?

**Comment by rhysd** [comment]
Highlighting matches is a feature only for built-in ripgrep. So it is not available when using hgrep with `grep -nH`. This is a limitation of the format of `-nH` option. It does not include column numbers of the match so it is not possible to know the match positions.

**Comment by sdbbs** [comment]
I do not want to reopen the issue, just wanted to say many thanks for the answer, @rhysd - that explains it. And also wanted to comment on this:

> It does not include column numbers of the match so it is not possible to know the match positions.

If one uses `grep --color=always`, then wouldn't it be possible to look for the ANSI color escape codes, and use their positions as match positions? If we do `grep --color=always foo myfile.c > out.txt`, we can see that e.g. last line match is actually `int myvar = [01;31m[Kfoo[m[K(42, 28);`, where `[01;31m[K` would be start of (default grep) red color for match, and `[m[K` for end of match ... Or in other words - if `` = 0x1B = ESC = `\e` = `^[`, then `^[[01;31m^[[K` would represent the start of match, and `^[[m^[[K` the end of match.

**Comment by mitchcapper** [comment]
yes @sdbbs  is right one could parse the color codes, although non default codes etc cause issue and parsing adds overhead and complexity.   Another option would be to pass the highlight term to hgrep with an optional arg.   I think the best option would probably be just something like `--grep-in` arg and then you could do something like `grep MyKeyword | hgrep --grep-in MyKeyword` .   Yes hgrep would be re-searching for the match on the line specified, but this is decently low overhead and only an option to enable.   

The reason being to potentially allow say sorting or alternate programs to feed hgrep grep compatible data without losing  the highlighting match hgrep provides.    An alternative I currently do is to exact the matched files and pass them as args to hgrep and have it regrep each completely.  Not pretty (or efficient) but works.
