### ISSUE TITLE
hgrep on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [rhysd/hgrep#3]
Hi,

I've packaged and merged `hgrep` into the main pkgsrc branch, https://mail-index.netbsd.org/pkgsrc-changes/2021/10/20/msg242216.html

This means the package is now available from the official repositories for NetBSD.

Thank you for this awesome tool.
/pin

**Comment by 0323pin** [comment]
Hi,

I really dislike GitHub, I only have an account to be able to communicate with projects host here, otherwise I keep my own stuff at codeberg.

Hope it's fine I post here in md format.

### NetBSD

To install pre-built binaries using the package manager, simply run

`pkgin install hgrep`

Or, if you prefer to build from source,

```
cd /usr/pkgsrc/textproc/hgrep
make install
```

Thank you.

**Comment by rhysd** [comment]
OK, no problem. I'll add it myself. Thank you for telling me the instruction.
