### ISSUE TITLE
Musl binary

### ISSUE THREAD

**Issue by elkarouh** [rhysd/hgrep#5]
Hi
Is it possible to provide a musl-binary (the way ripgrep does)?
(i use an old linux machine that i cannot upgrage)

Many thanks

**Comment by rhysd** [comment]
Doesn't `cargo install` work on the machine?

**Comment by rhysd** [comment]
Please find and try the binary in this page.

https://github.com/rhysd/hgrep/releases/tag/v0.1.9

**Comment by elkarouh** [comment]
Hi,
When trying to run, i get the following error message
`zsh: no such file or directory: ./hgrep`

**Comment by rhysd** [comment]
Please describe what you tried

**Comment by elkarouh** [comment]
I just did:
./hgrep
