### ISSUE TITLE
[Feature Request] Pre-compiled binary for linux-arm64

### ISSUE THREAD

**Issue by 4513ECHO** [rhysd/hgrep#9]
Could you release binary for linux with arm64(aarch64) architecture?
Thank you.

**Comment by rhysd** [comment]
I added Linux AArch64 build to the release job on `linux-aarch64` branch. Can you download the built binary and check if `hgrep --version` works fine on your AArch64 Linux machine?

https://github.com/rhysd/hgrep/suites/6187952685/artifacts/217716050

If it works, I'll merge the branch and release a new version of hgrep.

**Comment by 4513ECHO** [comment]
```console
$ ~/hgrep-v0.0.0-aarch64-unknown-linux-gnu/hgrep --version
hgrep 0.2.4
```

OK, It works correctly.

**Comment by rhysd** [comment]
Thank you for confirming that.

**Comment by rhysd** [comment]
v0.2.5 was released: https://github.com/rhysd/hgrep/releases/tag/v0.2.5
